PlayerMessage: '§b➣ §7%PlayerName% &c%Distance% &7'
Empty: '&7пусто'
NearMessage: '§7Игроки в радиусе §d%RADIUS%§7 блоков: '
NoPerm: '&cУ вас нет прав!'
position: 'X:&d%X% &7Y:&d%Y% &7Z:&d%Z%'
#ПОКАЗЫВАТЬ ЛИ ИГРОКОВ В ГМ 3
gamemode3: false
#ПОКАЗЫВАТЬ ЛИ ИГРОКОВ В НЕВИДИМОСТИ
invisibility: false
# РАСПОЛОГАТЬ ПЕРМИШОНЫ ПО ВОЗРАСТАНИЮ
# <НАЗВАНИЕ ПЕРМА (БЕЗ ТОЧКИ)>: <РАДИУС ЦЕЛЫМ ЧИСЛОМ>
# ПОСЛЕ СОЗДАНИЯ ПРОПИСЫВАЕМ /NEAR RELOAD И ВЫДАЕМ ИГРОКАМ ПЕРМЫ
perms:
  SuperNear100: 100
  SuperNear200: 200
  SuperNear300: 300
  SuperNear400: 400
  SuperNear500: 500
  SuperNear600: 600
Exception:
- Пусто...
