#ЦВЕТ СКОБОЧКИ.
ColourBracket: '&7'
#ЦВЕТ ДИСТАНЦИИ МЕЖДУ ИГРОКАМИ
ColourDistanse: '&c'
#ОТОБРАЖАЕТСЯ КОГДА В РАДИУСЕ НИКОГО НЕТ
Empty: '&7пусто'
#ТУТ ВСЕ ПОНЯТНО
NearMessage: '§7Игроки в радиусе §d%RADIUS%§7 блоков: '
#КОГДА НЕТ ПРАВ
NoPerm: '&cУ вас нет прав!'
# РАСПОЛОГАТЬ ПЕРМИШОНЫ ПО ВОЗРАСТАНИЮ
# <НАЗВАНИЕ ПЕРМА (БЕЗ ТОЧКИ)>: <РАДИУС ЦЕЛЫМ ЧИСЛОМ>
# ПОСЛЕ СОЗДАНИЯ ПРОПИСЫВАЕМ /NEAR RELOAD И ВЫДАЕМ ИГРОКАМ ПЕРМЫ
perms:
  SuperNear100: 100
  SuperNear200: 200
  SuperNear300: 300
  SuperNear400: 400
  SuperNear500: 500
  SuperNear600: 600