#ЦВЕТ СКОБОЧКИ.
ColourBracket: '&7'
#ЦВЕТ ДИСТАНЦИИ МЕЖДУ ИГРОКАМИ
ColourDistanse: '&c'
#ОТОБРАЖАЕТСЯ КОГДА В РАДИУСЕ НИКОГО НЕТ1
Empty: '&7пусто'
#ТУТ ВСЕ ПОНЯТНО
NearMessage: '§7Игроки в радиусе §d %RADIUS% §7 блоков: '
# КОГДА НЕТ ПРАВ
NoPerm: '&cУ вас нет прав!'